project:
  type: book
  output-dir: docs
    
book:
  title: "Mapping"
  subtitle: "Materials for an *In Development* Course on GIS & Mapping"
  author: "Andrew Grogan-Kaylor"
  date: "today"
  twitter-card: true
  open-graph: true
  site-url: https://agrogan1.github.io/mapping
  search: true
  repo-url: https://github.com/agrogan1/mapping
  repo-actions: [issue]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - courseoutline-5weeks.qmd
    - part: "Geographical and GIS Concepts"
      chapters: 
        - latitude-and-longitude.qmd
        - crs.qmd
    - part: "GIS Data"
      chapters:
        - shapefiles.qmd
        - shapefiles2.qmd
        - symbology.qmd
        - merge-with-external-data.qmd
    - part: "R Libraries"
      chapters: 
        - ggplot-map.qmd
        - location-data.qmd
    - part: "More Advanced GIS Concepts"
      chapters: 
        - geocoding.qmd
  navbar:
    background: primary
    
google-scholar: true

format:
  html:
   theme: 
      light: united
      dark: vapor
   css: mapping.css
   execute:
      freeze: auto

