project:
  type: book
  output-dir: docs
    
book:
  title: "Mapping"
  subtitle: "Materials for an *In Development* Course on GIS & Mapping"
  author: "Andrew Grogan-Kaylor"
  date: "today"
  twitter-card: true
  open-graph: true
  site-url: https://agrogan1.github.io/mapping
  search: true
  repo-url: https://github.com/agrogan1/mapping
  repo-actions: [issue]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - index.qmd
    - shapefiles.qmd
    - shapefiles2.qmd
  navbar:
    background: primary
    
google-scholar: true

format:
  html:
   theme: 
      light: united
      dark: vapor



