project:
  type: book
  output-dir: docs
    
book:
  title: "Mapping"
  subtitle: "Materials for an *In Development* Course on GIS & Mapping"
  author: "Andrew Grogan-Kaylor"
  date: "today"
  twitter-card: true
  open-graph: true
  favicon: logo-compass.png
  site-url: https://agrogan1.github.io/mapping
  search: true
  repo-url: https://github.com/agrogan1/mapping
  repo-actions: [issue]
  sharing: [twitter, facebook, linkedin]
  chapters:
    - part: "Introduction"
      chapters:
        - index.qmd
        - courseoutline.qmd
        - R.qmd
    - part: "Geographical and GIS Concepts"
      chapters: 
        - latitude-and-longitude.qmd
        - projections.qmd
        - crs.qmd
    - part: "GIS Data"
      chapters:
        - sf.qmd
        - shapefiles.qmd
        - shapefiles2.qmd
        - inspecting.qmd
        - symbology.qmd
        - rnaturalearth.qmd
        - WDI.qmd
    - part: "Mapping With `ggplot`"
      chapters: 
        - ggplot-map.qmd
        - merge-with-external-data.qmd
        - location-data.qmd
    - part: "More Advanced GIS Concepts"
      chapters: 
        - geocoding.qmd
        - cartogram.qmd
    - part: "Other R Libraries for Mapping"
      chapters:
        - leaflet.qmd
        - plotly.qmd
  navbar:
    background: primary
    
google-scholar: true

format:
  html:
   theme: 
      light: united
      dark: vapor
   css: mapping.css
   lightbox: true
   code-summary: "Show the code"
   execute:
      freeze: auto

