---
title: "Leaflet Map Test"
description: |
  A demonstration map created using `leaflet`.
author:
- name: Andy Grogan-Kaylor
  url: https://agrogan1.github.io/
  affiliation: University of Michigan
  affiliation_url: https://umich.edu/
date: '`r Sys.Date()`'
output: 
  distill::distill_article:
    highlight: haddock
    toc: yes
    toc_float: yes
    code_folding: true
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = FALSE)

```

# Call Libraries

```{r}

library(leaflet) # web based maps

library(sf) # simple (spatial) features

library(readr) # import csv

library(dplyr) # data wrangling

library(here) # where am I?

# setwd(here()) # set the working directory

```

# Get Simulated Client Data

```{r}

clients <- read_csv("location-data/clients.csv")

```

# Only Clients In Ann Arbor Area

```{r}

clients <- clients %>% 
  filter(latitude <= 42.35 &
           latitude >= 42.2 &
           longitude >= -83.8 &
           longitude <= -83.65)

```

# Shapefiles

```{r}

parks <- read_sf("shapefiles/AA_Parks/AA_Parks.shp")

university <- read_sf("shapefiles/AA_University/AA_University.shp")

city_boundary <- read_sf("shapefiles/AA_City_Boundary/AA_City_Boundary.shp")

```

# Transform CRS

> see https://stackoverflow.com/questions/66471147/how-to-plot-sp-object-as-sf-in-r-leaflet

```{r}

university <- st_transform(university, 4326) # transform CRS

parks <- st_transform(parks, 4326) # transform CRS

city_boundary <- st_transform(city_boundary, 4326) # transform CRS

```


# Leaflet Map

## Color Palette

```{r}

pal <- colorFactor(c("red", "blue", "orange", "green"), 
                   domain = levels(as.factor(clients$program)))

```

## Map

```{r, fig.height=8}

leaflet(clients) %>%
  setView(lng = mean(clients$longitude), 
          lat = mean(clients$latitude), 
          zoom = 12) %>% 
  # addTiles() %>%
  addProviderTiles(providers$Stamen.TonerLite) %>%
  addCircleMarkers(~longitude, 
             ~latitude, 
             popup = ~paste("Client ID:", as.character(ID)), 
             label = ~paste("Client ID:", as.character(ID)),
             color = ~pal(program),
             clusterOptions = markerClusterOptions()) %>%
  addLegend("bottomright", 
            pal = pal, 
            values = ~program,
            title = "Program") %>%
  # addPolygons(data = parks, color = "green") %>%
  # addPolygons(data = university, color = "blue") %>%
  addPolygons(data = city_boundary, color = "red",
              fillOpacity = 0.0)

```







