---
title: "Latitude and Longitude"
description: |
  An evolving tutorial.
author: "Andy Grogan-Kaylor"
date: "`r Sys.Date()`"
output:
  distill::distill_article:
    highlight: haddock
    toc: yes
    code_folding: true
---

```{r setup, include=FALSE}

knitr::opts_chunk$set(echo = TRUE)

```

# Call the Libraries

```{r}

library(plotly)

```

# Generate Some Random Coordinates

```{r}

N <- 10 # number of points

# latitude from -90 to +90

latitude <- runif(N, min = -90, max = 90) 

# longitude from + -180 to + 180

longitude <- runif(N, min = -180, max = 180) 

# 1st point reset to 0, 0

latitude[1] <- 0

longitude[1] <- 0

# label

label <- LETTERS[1:N] # label with letters of alphabet

# dataframe

mydata <- data.frame(latitude, longitude, label)

mydata # replay

```

# Map The Coordinates

```{r}

mymap <- plot_geo(mydata) %>%
  add_markers(x = ~longitude,
              y = ~latitude,
              color = ~label,
              colors = "Spectral") %>%
  layout(title = "Randomly Generated Coordinates")

mymap # replay

```

