---
title: "Client Data With Latitude and Longitude"
author: "Andy Grogan-Kaylor"
date: "today"
format:
  html:
    toc: true
    number-sections: true
    code-fold: false
    theme:
      light: united
      dark: vapor
---

# Call Libraries

```{r}
#| output: false

library(readr) # import CSV

library(ggplot2) # map

library(sf) # simple (spatial) features

library(dplyr) # data wrangling

```

# Get Data

## Client Data With Latitude and Longitude

```{r}
#| output: false

clients <- read_csv("clients.csv")

clients # replay

```

## Only Clients in Ann Arbor Area

```{r, eval = TRUE}

clients <- clients %>% 
  filter(latitude <= 42.33 &
           latitude >= 42.22 &
           longitude >= -83.8 &
           longitude <= -83.65)

```

## Attach CRS to Clients and Convert to `sf`

```{r}

# 4269 -> NAD1983 (A2 is NAD1983)

points <- st_as_sf(clients, 
                  coords = c("longitude", "latitude"), 
                  crs = 4269) 

```

## Get Shapefile

```{r}

city_boundary <- read_sf("../shapefiles/AA_City_Boundary/AA_City_Boundary.shp")

```

# Map

```{r}

ggplot(city_boundary) +
  geom_sf(color = "red") +
  geom_sf(data = points, aes(color = program)) +
  scale_color_viridis_d(name = "Program") +
  theme_minimal()

```









