---
title: "Symbology"
author: "Andrew Grogan-Kaylor"
date: "today"
format:
  html:
    toc: true
    number-sections: true
    theme:
      light: cosmo
      dark: vapor
    code-fold: true
    code-summary: "Show the code"
---

# Introduction

[Shapefiles](../shapefiles/shapefiles.html) are a standard format for storing geographic data. 

[Shapefiles](../shapefiles/shapefiles.html) generally come in three types: points; lines, and polygons. *Symbology* is the idea of using shapefile attributes to encode *quantitative* or *qualitative* information, such as income or program participation.

# Symbology

| Shapefile Type | Symbology|
|----------------|----------|
| Points         | Size: ● <span style="font-size:2em">●</span> <span style="font-size:3em">●</span>|  
|                | Color: <span style="color:red">●</span> <span style="color:blue">●</span> <span style="color:green">●</span>|
| Lines | Width: ━ <span style="font-size:2em">━</span> <span style="font-size:3em">━</span>|
| | Color: <span style="color:red;font-size:2em">━</span> <span style="color:blue;font-size:2em">━</span> <span style="color:green;font-size:2em">━</span> |
| | Pattern: <span style="font-size:2em">━ ┅</span> | 
| Polygons | Color: <span style="color:red;font-size:3em">■</span> <span style="color:blue;font-size:3em">■</span> <span style="color:green;font-size:3em">■</span>|
| | Pattern: <span style="font-size:3em">■ ▤ ▦</span>

: Symbology


# A Note About the Use of Color

Color palettes can be either qualitative or quantitative in nature. 

```{r}

library(RColorBrewer) # A library for color palettes

```

```{r}
#| fig.cap: "Blues Palette"
#| fig.height: 3

display.brewer.pal(name = "Blues", n = 9)

```

```{r}
#| fig.cap: "Spectral Palette"
#| fig.height: 3

display.brewer.pal(name = "Spectral", n = 9)

```

```{r}
#| fig.cap: "Set1 Palette"
#| fig.height: 3

display.brewer.pal(name = "Set1", n = 9)

```

